# MyPi completion                                          -*- shell-script -*-

# This bash completions script was generated by
# completely (https://github.com/dannyben/completely)
# Modifying it manually is not recommended

_MyPi_completions_filter() {
  local words="$1"
  local cur=${COMP_WORDS[COMP_CWORD]}
  local result=()

  if [[ "${cur:0:1}" == "-" ]]; then
    echo "$words"
  
  else
    for word in $words; do
      [[ "${word:0:1}" != "-" ]] && result+=("$word")
    done

    echo "${result[*]}"

  fi
}

_MyPi_completions() {
  local cur=${COMP_WORDS[COMP_CWORD]}
  local compwords=("${COMP_WORDS[@]:1:$COMP_CWORD-1}")
  local compline="${compwords[*]}"

  case "$compline" in
    'nfs-export'*)
      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_MyPi_completions_filter "--config --export -e --directory -d --host --ip -i --options -o --use-config --no-use-config --no-config")" -- "$cur" )
      ;;

    'add-fstab'*)
      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_MyPi_completions_filter "--config --line -l --file-system --fs --mount-point --mount --type --options --dump --pass --use-config --no-use-config --no-config")" -- "$cur" )
      ;;

    'install'*)
      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_MyPi_completions_filter "apt docker docker-cmd git omz --config --apt -a --git -g --git-clone-dir --clone-dir --gcd --docker -d --mkdir --mkdir-opt --fstab --nfs-export --post-install --omz-plugin --apt-cmd --desktop --de --apt-install --no-apt-install --no-apt --git-install --no-git-install --install-docker --no-install-docker --docker-install --no-docker-install --install-nfs --no-install-nfs --reboot --no-reboot --install-omz --no-install-omz --install-desktop --no-install-desktop --no-desktop --no-de")" -- "$cur" )
      ;;

    'updater'*)
      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_MyPi_completions_filter "--config --shutdown --use-config --no-use-config --no-config --apt --no-apt --git --no-git --docker --no-docker --dist-upgrade --no-dist-upgrade --apt-clean --no-apt-clean --reboot --no-reboot")" -- "$cur" )
      ;;

    *)
      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_MyPi_completions_filter "add-fstab install nfs-export updater")" -- "$cur" )
      ;;

  esac
} &&
complete -F _MyPi_completions MyPi

# ex: filetype=sh
